# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-tgw-hub-connector
  description: This component is responsible for provisioning an [AWS Transit Gateway Peering Connection](https://aws
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component
